pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    APP_DIR = "java-maven-sonar-argocd-helm-k8s/spring-boot-app"
    DOCKER_IMAGE = "abhishekf5/ultimate-cicd:${BUILD_NUMBER}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Test') {
      steps {
        sh "cd ${APP_DIR} && mvn clean package"
      }
    }

    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh "cd ${APP_DIR} && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN"
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          sh "cd ${APP_DIR} && docker build -t ${DOCKER_IMAGE} ."
          docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
            docker.image(DOCKER_IMAGE).push()
          }
        }
      }
    }
  }
}
